FROM python:3-slim
EXPOSE 8000:8000
STOPSIGNAL SIGINT
WORKDIR /app
COPY . .
RUN pip install --no-cache-dir ".[web]"
CMD [ "python", "-m", "flask", "--app", "src.gpxtable.wsgi:create_app()", "run", "--host", "0.0.0.0", "--port", "8000" ]

